import React, { useEffect, useState } from 'react';
import { AccessibilityInfo, LayoutAnimation, Linking, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import * as Crypto from 'expo-crypto';
import { Orb } from '../src/components/Orb';
import { useNura } from '../src/state/NuraContext';
import { useAIState } from '../src/state/AIStateContext';
import { AgentAnswer, AgentEvent, AgentSource, AgentTrace, getAgentStatus, runNuraAgent } from '../src/services/agentClient';

const C = { bg: '#F7F6F8', ink: '#282530', muted: '#77727F', quiet: '#9993A0', line: '#E5E1E8', white: '#FFFFFF', plum: '#483250', blue: '#1264F5', paleBlue: '#EAF1FF', amber: '#FFF3DD', amberInk: '#754D18', green: '#E4F2E9', lilac: '#F0EAF5', redInk: '#8B3D39', red: '#FFF0ED' };
const urgentPrompts = [
  { id: 'breathing', title: 'New severe trouble breathing or chest pain', detail: 'If you selected this, don’t wait for an app response.', url: 'https://www.cdc.gov/heart-disease/about/heart-attack.html' },
  { id: 'stroke', title: 'Sudden face or arm weakness, speech trouble, or severe confusion', detail: 'If you selected this, seek emergency help now.', url: 'https://www.cdc.gov/stroke/signs-symptoms/index.html' },
  { id: 'other', title: 'Another symptom feels immediately dangerous or is rapidly worsening', detail: 'Trust your sense of urgency and contact local emergency services.' },
];
type Severity = 'mild' | 'moderate' | 'severe';
const symptomAreas = ['Pain', 'Breathing', 'Digestive', 'Skin', 'Sleep / energy', 'Other'];
const onsetOptions = ['Today', '1–3 days ago', '4–7 days ago', 'More than a week ago', 'Not sure'];

function ToggleRow({ title, detail, selected, onPress, disabled = false }: { title: string; detail: string; selected: boolean; onPress: () => void; disabled?: boolean }) {
  return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: selected, disabled }} disabled={disabled} onPress={onPress} style={[s.toggleRow, selected && s.toggleSelected, disabled && s.disabled]}><View style={[s.check, selected && s.checkSelected]}><Text style={s.checkText}>{selected ? '✓' : ''}</Text></View><View style={{ flex: 1 }}><Text style={s.toggleTitle}>{title}</Text><Text style={s.toggleDetail}>{detail}</Text></View></Pressable>;
}

export default function Symptoms() {
  const { topics, addFact } = useNura();
  const { state: aiState, dispatchRunEvent } = useAIState();
  const [symptom, setSymptom] = useState('');
  const [symptomArea, setSymptomArea] = useState('');
  const [onset, setOnset] = useState('');
  const [severity, setSeverity] = useState<Severity>('moderate');
  const [urgentIds, setUrgentIds] = useState<string[]>([]);
  const [urgent, setUrgent] = useState(false);
  const [consentOpen, setConsentOpen] = useState(false);
  const [shareTopics, setShareTopics] = useState(false);
  const [shareExternalSearch, setShareExternalSearch] = useState(false);
  const [service, setService] = useState<{ available: boolean; reason?: string; capabilities?: { trustedHealthSearch?: boolean } } | null>(null);
  const [busy, setBusy] = useState(false);
  const [answer, setAnswer] = useState<AgentAnswer | null>(null);
  const [sources, setSources] = useState<AgentSource[]>([]);
  const [publicSearchUsed, setPublicSearchUsed] = useState(false);
  const [trace, setTrace] = useState<AgentTrace[]>([]);
  const [error, setError] = useState('');
  const [saved, setSaved] = useState(false);
  const [reducedMotion, setReducedMotion] = useState(false);
  const hasUrgent = urgentIds.length > 0 || severity === 'severe';
  const showUrgent = urgent || hasUrgent;

  useEffect(() => {
    let mounted = true;
    void getAgentStatus().then((status) => { if (mounted) setService(status); });
    AccessibilityInfo.isReduceMotionEnabled().then((value) => { if (mounted) setReducedMotion(value); });
    const subscription = AccessibilityInfo.addEventListener('reduceMotionChanged', setReducedMotion);
    return () => { mounted = false; subscription.remove(); };
  }, []);

  function toggleUrgent(id: string) {
    if (showUrgent) return;
    if (!reducedMotion) LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    setUrgentIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  }
  function setLevel(next: Severity) {
    if (showUrgent) return;
    if (!reducedMotion) LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    setSeverity(next);
  }
  function start() {
    if (showUrgent) { setUrgent(true); return; }
    if (!symptomArea) { setError('Choose the symptom area you want Nura to help organize.'); return; }
    setError(''); setConsentOpen(true);
  }
  async function send() {
    if (!symptom.trim() || busy) return;
    setConsentOpen(false); setBusy(true); setError(''); setAnswer(null); setSources([]); setPublicSearchUsed(false); setTrace([]); setSaved(false);
    const runId = Crypto.randomUUID();
    const question = `I am asking for bounded, non-diagnostic symptom support. Symptom area selected by the user: ${symptomArea}. When it started, from a fixed choice: ${onset || 'not provided'}. My own severity selection: ${severity}. Do not diagnose. Help me understand what my saved records can and cannot say, and offer safe next steps with cited general sources only if they are retrieved.`;
    const context = {
      facts: [],
      topics: shareTopics ? topics.map(({ id, label }) => ({ id, label })) : [],
      links: [],
    };
    dispatchRunEvent('RUN_STARTED');
    let runTrace: AgentTrace[] = [];
    try {
      await runNuraAgent({ runId, mode: 'symptom_support', question, consentConfirmed: true, history: [], externalSearchConsent: shareExternalSearch, treatmentContextConsent: false, visitContextConsent: false, context: { ...context, treatments: [], visits: [] } }, (event: AgentEvent) => {
        if (event.type === 'trace') {
          const item = { id: event.id, label: event.label, status: event.status, detail: event.detail };
          runTrace = [...runTrace.filter((existing) => existing.id !== event.id), item]; setTrace(runTrace);
          if (!reducedMotion) LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
        } else if (event.type === 'evidence') { setSources(event.sources); setPublicSearchUsed((current) => current || event.sources.some((source) => source.kind === 'external_source')); }
        else if (event.type === 'answer') { setAnswer({ answer: event.answer, citations: event.citations, unknowns: event.unknowns, nextSteps: event.nextSteps, coverageAssessments: event.coverageAssessments, memoryProposal: null }); dispatchRunEvent('TEXT_MESSAGE_START'); }
        else if (event.type === 'run_finished') dispatchRunEvent('RUN_FINISHED');
        else if (event.type === 'run_error') { setError(event.message); dispatchRunEvent('RUN_ERROR'); }
      });
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : 'Nura could not complete this response.'); dispatchRunEvent('RUN_ERROR');
    } finally { setBusy(false); void getAgentStatus().then(setService); }
  }
  function saveNote() {
    if (saved || !symptom.trim()) return;
    const value = [`Area: ${symptomArea || 'not selected'}`, symptom.trim() ? `Your note: ${symptom.trim()}` : '', onset ? `Started: ${onset}` : '', `Your severity selection: ${severity}`].filter(Boolean).join(' · ');
    addFact('Symptom note', value, { category: 'Symptoms', source: 'Entered by you · saved at your request', note: 'A user-authored note; not a diagnosis or clinician assessment.' });
    setSaved(true);
  }
  function reset() {
    if (!reducedMotion) LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    setUrgent(false); setUrgentIds([]); setSeverity('moderate'); setSymptom(''); setSymptomArea(''); setOnset(''); setAnswer(null); setSources([]); setPublicSearchUsed(false); setTrace([]); setError(''); setSaved(false);
  }

  return <View style={s.page}>
    <StatusBar style="dark" />
    {showUrgent ? <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
      <Text style={s.overline}>NURA · IMMEDIATE SAFETY</Text>
      <View style={s.urgentBanner}><Text style={s.urgentMark}>!</Text><View style={{ flex: 1 }}><Text style={s.urgentTitle}>Get help now.</Text><Text style={s.urgentBody}>You selected an urgent warning sign. Please contact your local emergency service now. Don’t wait for Nura or continue this questionnaire.</Text></View></View>
      <View style={s.card}><Text style={s.sectionLabel}>WHAT YOU SELECTED</Text>{urgentIds.map((id) => { const item = urgentPrompts.find((option) => option.id === id); return item ? <View key={id} style={s.urgentLine}><Text style={s.urgentBullet}>•</Text><Text style={s.body}>{item.title}</Text></View> : null; })}{severity === 'severe' && <View style={s.urgentLine}><Text style={s.urgentBullet}>•</Text><Text style={s.body}>You described this as severe or rapidly worsening.</Text></View>}</View>
      <View style={s.card}><Text style={s.sectionLabel}>TRUSTED SAFETY INFORMATION</Text><Text style={s.body}>Sudden stroke warning signs and heart attack symptoms need urgent action. Nura cannot assess an emergency or replace local emergency services.</Text><Pressable accessibilityRole="link" onPress={() => void Linking.openURL('https://www.cdc.gov/stroke/signs-symptoms/index.html')} style={s.sourceLink}><Text style={s.sourceLinkText}>CDC · Stroke warning signs ↗</Text></Pressable><Pressable accessibilityRole="link" onPress={() => void Linking.openURL('https://www.cdc.gov/heart-disease/about/heart-attack.html')} style={s.sourceLink}><Text style={s.sourceLinkText}>CDC · Heart attack symptoms ↗</Text></Pressable></View>
      <Pressable accessibilityRole="button" onPress={() => router.replace('/(tabs)/home')} style={s.homeAction}><Text style={s.homeActionText}>RETURN TO YOUR HEALTH HOME</Text><Text style={s.homeArrow}>→</Text></Pressable>
      <Pressable accessibilityRole="button" onPress={() => { setUrgent(false); setUrgentIds([]); setSeverity('moderate'); }} style={s.secondary}><Text style={s.secondaryText}>I selected that by mistake · return to the check</Text></Pressable>
    </ScrollView> : <>
      <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
        <Pressable accessibilityRole="button" onPress={() => router.back()} style={s.back}><Text style={s.backText}>‹  BACK</Text></Pressable>
        <View style={s.hero}><View style={s.heroOrb}><Orb size={40} /></View><Text style={s.overline}>SYMPTOM SUPPORT · 09</Text><Text style={s.title}>What’s going on?</Text><Text style={s.heroBody}>Describe what you’re noticing. Nura can help organize your information and find safe next steps; it cannot diagnose.</Text></View>
        <View style={s.warning}><Text style={s.warningIcon}>!</Text><View style={{ flex: 1 }}><Text style={s.warningTitle}>Could this be an emergency?</Text><Text style={s.warningBody}>If symptoms are severe, rapidly worsening, or feel immediately dangerous, contact local emergency services now. This check does not determine whether you are safe.</Text></View></View>
        <View style={s.card}><Text style={s.sectionLabel}>FIRST, CHECK FOR URGENT SIGNS</Text>{urgentPrompts.map((item) => <ToggleRow key={item.id} title={item.title} detail={item.detail} selected={urgentIds.includes(item.id)} onPress={() => toggleUrgent(item.id)} />)}
          <Text style={s.sectionLabel}>HOW SEVERE DOES IT FEEL TO YOU?</Text><View style={s.severityRow}>{(['mild', 'moderate', 'severe'] as Severity[]).map((level) => <Pressable key={level} accessibilityRole="radio" accessibilityState={{ selected: severity === level }} onPress={() => setLevel(level)} style={[s.severity, severity === level && s.severitySelected]}><Text style={[s.severityText, severity === level && s.severityTextSelected]}>{level === 'severe' ? 'Severe / worsening' : level[0].toUpperCase() + level.slice(1)}</Text></Pressable>)}</View>
          {hasUrgent && <View accessibilityLiveRegion="assertive" style={s.inlineEscalation}><Text style={s.inlineEscalationText}>This flow has stopped. Continue to the immediate safety screen.</Text><Pressable accessibilityRole="button" onPress={() => setUrgent(true)} style={s.escalateButton}><Text style={s.escalateButtonText}>SHOW URGENT ACTIONS  →</Text></Pressable></View>}
        </View>
        <View style={s.card}><Text style={s.sectionLabel}>CHOOSE A GENERAL AREA</Text><View style={s.areaChoices}>{symptomAreas.map((area) => <Pressable key={area} accessibilityRole="radio" accessibilityState={{ selected: symptomArea === area }} onPress={() => setSymptomArea(area)} style={[s.areaChoice, symptomArea === area && s.areaChoiceSelected]}><Text style={[s.areaChoiceText, symptomArea === area && s.areaChoiceTextSelected]}>{area}</Text></Pressable>)}</View><Text style={[s.fieldLabel, { marginTop: 14 }]}>WHEN DID IT START?</Text><View style={s.onsetChoices}>{onsetOptions.map((item) => <Pressable key={item} accessibilityRole="radio" accessibilityState={{ selected: onset === item }} onPress={() => setOnset(item)} style={[s.onsetChoice, onset === item && s.onsetChoiceSelected]}><Text style={[s.onsetChoiceText, onset === item && s.onsetChoiceTextSelected]}>{item}</Text></Pressable>)}</View></View><View style={s.card}><Text style={s.sectionLabel}>YOUR PRIVATE NOTE · OPTIONAL</Text><TextInput value={symptom} onChangeText={setSymptom} editable={!hasUrgent && !busy} placeholder="Add details for your own record" placeholderTextColor={C.quiet} style={s.input} multiline maxLength={900} accessibilityLabel="Private symptom note" /><Text style={s.helper}>This text stays on this screen and is not sent to Nura or a search service. It is saved only if you choose “Save symptom note”. Nura receives only the area, fixed onset choice, severity, and selected health areas you approve.</Text></View>
        <View style={s.card}><Text style={s.sectionLabel}>OPTIONAL PROFILE CONTEXT</Text><Text style={s.body}>Nura can use the health areas you selected. Saved medical records and medicine/treatment entries are not included in this symptom flow.</Text><ToggleRow title="Health areas I selected" detail={`${topics.length} chosen areas · not diagnoses`} selected={shareTopics} onPress={() => setShareTopics((value) => !value)} /></View>
        <View style={s.scopeNote}><Text style={s.scopeIcon}>i</Text><Text style={s.scopeText}>Your symptom details are not saved as a conversation. Nura sends nothing until you review the sharing choices and continue.</Text></View>
        {service?.available === false && <View style={s.offline}><Text style={s.offlineTitle}>Nura is temporarily unavailable</Text><Text style={s.offlineBody}>{service.reason ?? 'You can still use the urgent-safety guidance above. No symptom information has been sent.'}</Text></View>}
        {error ? <View style={s.error}><Text style={s.errorTitle}>Nura couldn’t finish that response</Text><Text style={s.body}>{error}</Text><Text style={s.helper}>Your symptom note was not saved.</Text></View> : null}
        {answer && <View style={s.answerCard}><Text style={s.answerEyebrow}>BOUNDED, NON-DIAGNOSTIC RESPONSE</Text><Text style={s.answerText}>{answer.answer}</Text>{answer.unknowns.length > 0 && <View style={s.answerSection}><Text style={s.sectionLabel}>WHAT ISN’T KNOWN</Text>{answer.unknowns.map((item, index) => <Text key={`u-${index}`} style={s.listText}>•  {item}</Text>)}</View>}{answer.nextSteps.length > 0 && <View style={s.answerSection}><Text style={s.sectionLabel}>POSSIBLE NEXT STEPS</Text>{answer.nextSteps.map((item, index) => <Text key={`n-${index}`} style={s.listText}>•  {item}</Text>)}</View>}{sources.length > 0 && <View style={s.answerSection}><Text style={s.sectionLabel}>SOURCES CHECKED</Text>{sources.map((source) => <Pressable key={source.id} accessibilityRole="link" disabled={!source.url} onPress={() => { if (source.url) void Linking.openURL(source.url); }} style={s.evidence}><Text style={s.evidenceRef}>{source.reference}</Text><View style={{ flex: 1 }}><Text style={s.evidenceTitle}>{source.title}</Text><Text style={s.evidenceDetail}>{source.source}{source.date ? ` · ${source.date}` : ''}</Text></View><Text style={s.evidenceArrow}>↗</Text></Pressable>)}</View>}{!publicSearchUsed && <View style={s.sourceGap}><Text style={s.sourceGapText}>No trusted public medical source was cited for this answer. Use it only to organize your question for a clinician.</Text></View>}<Text style={s.disclaimer}>This does not identify the cause of a symptom or replace care from a qualified clinician. If symptoms become severe, rapidly worsen, or feel dangerous, contact local emergency services.</Text><Pressable accessibilityRole="button" disabled={saved} onPress={saveNote} style={[s.saveNote, saved && s.savedNote]}><Text style={[s.saveNoteText, saved && s.savedNoteText]}>{saved ? 'SYMPTOM NOTE SAVED TO YOUR PROFILE' : 'SAVE SYMPTOM NOTE TO MY PROFILE'}</Text></Pressable><Text style={s.helper}>Only the note you choose is saved. The AI response and activity trace are not added to your history.</Text><Pressable accessibilityRole="button" onPress={reset} style={s.secondary}><Text style={s.secondaryText}>Start another symptom note</Text></Pressable></View>}
        {busy && <View style={s.liveCard}><View style={s.liveHeader}><Orb size={30} state={aiState} /><View style={{ flex: 1 }}><Text style={s.liveTitle}>{aiState === 'responding' ? 'Preparing the response' : 'Checking the selected context'}</Text><Text style={s.helper}>Live updates · what Nura is checking</Text></View></View>{trace.map((item) => <View key={item.id} style={s.traceRow}><View style={[s.traceDot, item.status === 'complete' && s.traceDone]} /><View style={{ flex: 1 }}><Text style={s.traceTitle}>{item.label}</Text>{item.detail ? <Text style={s.traceDetail}>{item.detail}</Text> : null}</View><Text style={s.traceStatus}>{item.status === 'complete' ? 'DONE' : 'NOW'}</Text></View>)}</View>}
        {!answer && !busy && <Pressable accessibilityRole="button" disabled={!symptomArea || hasUrgent} onPress={start} style={[s.primary, (!symptomArea || hasUrgent) && s.primaryDisabled]}><View><Text style={s.primaryTitle}>ASK NURA FOR SAFE NEXT STEPS</Text><Text style={s.primarySub}>Review sharing choices first</Text></View><Text style={s.primaryArrow}>→</Text></Pressable>}
        <View style={s.sourceNote}><Text style={s.sourceNoteText}>Safety references: <Text onPress={() => void Linking.openURL('https://www.cdc.gov/stroke/signs-symptoms/index.html')} style={s.sourceLinkText}>CDC stroke signs</Text> · <Text onPress={() => void Linking.openURL('https://www.cdc.gov/heart-disease/about/heart-attack.html')} style={s.sourceLinkText}>CDC heart attack symptoms</Text>.</Text></View>
      </ScrollView>
    </>}
    <Modal visible={consentOpen} transparent animationType={reducedMotion ? 'none' : 'slide'} onRequestClose={() => setConsentOpen(false)}><View style={[s.modalShade, Platform.OS === 'web' && s.modalShadeWeb]}><View style={[s.modalCard, Platform.OS === 'web' && s.modalCardWeb]}><View style={s.modalHandle} /><Text style={s.overline}>BEFORE NURA LOOKS</Text><Text style={s.modalTitle}>Choose what to include.</Text><Text style={s.body}>Nura receives only the symptom area, onset, severity and health areas you select. Your private note stays on this screen and is not sent. Saved records, medicines and files are not included. Your symptom details are not saved as a conversation or timeline event.</Text><View style={s.modalToggles}><ToggleRow title="Selected health areas" detail={`${shareTopics ? topics.length : 0} selected · not diagnoses`} selected={shareTopics} onPress={() => setShareTopics((value) => !value)} /><ToggleRow title="Search trusted public health sources" detail={service?.capabilities?.trustedHealthSearch ? (shareExternalSearch ? 'Only the selected area is used for a topic search' : 'Off · no public search') : 'Not available in this preview'} selected={shareExternalSearch} disabled={!service?.capabilities?.trustedHealthSearch} onPress={() => setShareExternalSearch((value) => !value)} /></View><Text style={s.helper}>If you turn this on, Nura may search trusted public health sites about the selected area. Your private note is not included.</Text><Pressable accessibilityRole="button" onPress={() => void send()} style={s.confirm}><Text style={s.confirmText}>CONTINUE WITH THESE DETAILS</Text><Text style={s.confirmArrow}>→</Text></Pressable><Pressable accessibilityRole="button" onPress={() => setConsentOpen(false)} style={s.cancel}><Text style={s.cancelText}>Not now · send nothing</Text></Pressable></View></View></Modal>
  </View>;
}

const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: C.bg }, content: { paddingHorizontal: 18, paddingTop: 44, paddingBottom: 28, maxWidth: 540, width: '100%', alignSelf: 'center' },
  back: { alignSelf: 'flex-start', minHeight: 32, justifyContent: 'center', marginBottom: 11 }, backText: { color: C.plum, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, overline: { color: '#897895', fontSize: 8, fontWeight: '800', letterSpacing: 1.4 }, hero: { borderRadius: 23, padding: 17, backgroundColor: '#EEEAF2', marginBottom: 12, overflow: 'hidden' }, heroOrb: { position: 'absolute', right: 12, top: 12, width: 52, height: 52, alignItems: 'center', justifyContent: 'center' }, title: { color: C.ink, fontSize: 29, lineHeight: 34, fontWeight: '400', letterSpacing: -1, marginTop: 10, maxWidth: 270 }, heroBody: { color: C.muted, fontSize: 11, lineHeight: 16, marginTop: 6, maxWidth: 300 },
  warning: { flexDirection: 'row', gap: 9, padding: 12, borderRadius: 15, borderWidth: 1, borderColor: '#EAD6B6', backgroundColor: C.amber, marginBottom: 12 }, warningIcon: { width: 20, height: 20, borderRadius: 10, textAlign: 'center', textAlignVertical: 'center', overflow: 'hidden', backgroundColor: '#F3D49D', color: C.amberInk, fontWeight: '800' }, warningTitle: { color: C.amberInk, fontSize: 10, fontWeight: '800' }, warningBody: { color: '#725F48', fontSize: 9, lineHeight: 13, marginTop: 3 },
  card: { padding: 13, borderRadius: 18, borderWidth: 1, borderColor: C.line, backgroundColor: C.white, marginBottom: 11 }, sectionLabel: { color: '#85748F', fontSize: 8, fontWeight: '800', letterSpacing: 1.05, marginBottom: 9 }, body: { color: C.muted, fontSize: 10, lineHeight: 15 }, toggleRow: { minHeight: 45, flexDirection: 'row', alignItems: 'center', gap: 9, paddingVertical: 7, paddingHorizontal: 8, marginBottom: 6, borderRadius: 12, borderWidth: 1, borderColor: C.line, backgroundColor: '#FBFAFC' }, toggleSelected: { borderColor: '#C7B6D0', backgroundColor: C.lilac }, disabled: { opacity: .48 }, check: { width: 18, height: 18, borderRadius: 6, borderWidth: 1, borderColor: '#BEB8C4', alignItems: 'center', justifyContent: 'center' }, checkSelected: { backgroundColor: C.plum, borderColor: C.plum }, checkText: { color: C.white, fontSize: 11, fontWeight: '800' }, toggleTitle: { color: C.ink, fontSize: 9, fontWeight: '700' }, toggleDetail: { color: C.muted, fontSize: 8, lineHeight: 12, marginTop: 2 },
  areaChoices: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, areaChoice: { minHeight: 34, paddingHorizontal: 10, borderRadius: 16, borderWidth: 1, borderColor: C.line, backgroundColor: '#FBFAFC', alignItems: 'center', justifyContent: 'center' }, areaChoiceSelected: { backgroundColor: C.blue, borderColor: C.blue }, areaChoiceText: { color: C.muted, fontSize: 8, fontWeight: '700' }, areaChoiceTextSelected: { color: C.white }, onsetChoices: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 7 }, onsetChoice: { minHeight: 31, paddingHorizontal: 9, borderRadius: 15, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' }, onsetChoiceSelected: { backgroundColor: C.plum, borderColor: C.plum }, onsetChoiceText: { color: C.muted, fontSize: 8, fontWeight: '600' }, onsetChoiceTextSelected: { color: C.white }, severityRow: { flexDirection: 'row', gap: 6, marginTop: 3 }, severity: { flex: 1, minHeight: 36, paddingHorizontal: 5, alignItems: 'center', justifyContent: 'center', borderRadius: 12, borderWidth: 1, borderColor: C.line, backgroundColor: '#FBFAFC' }, severitySelected: { backgroundColor: C.plum, borderColor: C.plum }, severityUrgent: { backgroundColor: '#A8473E', borderColor: '#A8473E' }, severityText: { color: C.muted, fontSize: 8, fontWeight: '700', textAlign: 'center' }, severityTextSelected: { color: C.white }, inlineEscalation: { padding: 10, borderRadius: 12, backgroundColor: C.red, marginTop: 9 }, inlineEscalationText: { color: C.redInk, fontSize: 9, fontWeight: '700', lineHeight: 13 }, escalateButton: { minHeight: 37, borderRadius: 11, backgroundColor: '#A8473E', alignItems: 'center', justifyContent: 'center', marginTop: 8 }, escalateButtonText: { color: C.white, fontSize: 8, fontWeight: '800', letterSpacing: .8 },
  input: { minHeight: 91, borderRadius: 13, borderWidth: 1, borderColor: C.line, backgroundColor: '#FBFAFC', padding: 11, color: C.ink, fontSize: 11, lineHeight: 16, textAlignVertical: 'top' }, onsetInput: { minHeight: 43, textAlignVertical: 'center' }, fieldLabel: { color: '#85748F', fontSize: 7, fontWeight: '800', letterSpacing: 1 }, helper: { color: C.quiet, fontSize: 8, lineHeight: 12, marginTop: 6 }, scopeNote: { flexDirection: 'row', gap: 8, padding: 10, borderRadius: 13, backgroundColor: '#F0EDF3', marginBottom: 10 }, scopeIcon: { color: C.plum, fontWeight: '800' }, scopeText: { flex: 1, color: C.muted, fontSize: 9, lineHeight: 13 }, offline: { padding: 12, borderRadius: 14, backgroundColor: C.amber, marginBottom: 10 }, offlineTitle: { color: C.amberInk, fontSize: 10, fontWeight: '800' }, offlineBody: { color: C.muted, fontSize: 9, lineHeight: 13, marginTop: 4 },
  primary: { minHeight: 55, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, borderRadius: 16, backgroundColor: C.blue, marginTop: 2 }, primaryDisabled: { opacity: .45 }, primaryTitle: { color: C.white, fontSize: 9, fontWeight: '800', letterSpacing: .7 }, primarySub: { color: '#DCE8FF', fontSize: 8, marginTop: 3 }, primaryArrow: { color: C.white, fontSize: 22, fontWeight: '300' }, sourceNote: { paddingHorizontal: 2, marginTop: 13 }, sourceNoteText: { color: C.quiet, fontSize: 8, lineHeight: 12 }, sourceLinkText: { color: '#1767D8', fontSize: 8, fontWeight: '700' },
  liveCard: { padding: 13, borderRadius: 18, borderWidth: 1, borderColor: '#DDD3E5', backgroundColor: C.white, marginTop: 10 }, liveHeader: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 8 }, liveTitle: { color: C.ink, fontSize: 11, fontWeight: '700' }, traceRow: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 35, borderTopWidth: 1, borderTopColor: '#F0EDF3' }, traceDot: { width: 8, height: 8, borderRadius: 5, backgroundColor: '#E8C17E' }, traceDone: { backgroundColor: '#75B68D' }, traceTitle: { color: C.ink, fontSize: 9, fontWeight: '600' }, traceDetail: { color: C.muted, fontSize: 8, marginTop: 2 }, traceStatus: { color: C.quiet, fontSize: 7, fontWeight: '800', letterSpacing: .7 },
  answerCard: { padding: 14, borderRadius: 19, borderWidth: 1, borderColor: '#D9CEE1', backgroundColor: C.white, marginTop: 11 }, answerEyebrow: { color: '#816D8F', fontSize: 8, fontWeight: '800', letterSpacing: 1.1 }, answerText: { color: C.ink, fontSize: 12, lineHeight: 18, marginTop: 9 }, answerSection: { borderTopWidth: 1, borderTopColor: C.line, paddingTop: 10, marginTop: 11 }, listText: { color: C.muted, fontSize: 10, lineHeight: 15, marginTop: 5 }, evidence: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#F0EDF3' }, evidenceRef: { color: '#1767D8', fontSize: 9, fontWeight: '800' }, evidenceTitle: { color: C.ink, fontSize: 9, fontWeight: '700' }, evidenceDetail: { color: C.muted, fontSize: 8, marginTop: 2 }, evidenceArrow: { color: '#1767D8', fontSize: 12 }, sourceGap: { padding: 9, backgroundColor: '#F5F2F7', borderRadius: 11, marginTop: 10 }, sourceGapText: { color: C.muted, fontSize: 8, lineHeight: 12 }, disclaimer: { color: C.muted, fontSize: 8, lineHeight: 12, marginTop: 11 }, saveNote: { minHeight: 43, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: C.blue, marginTop: 13 }, saveNoteText: { color: C.white, fontSize: 8, fontWeight: '800', letterSpacing: .7 }, savedNote: { backgroundColor: C.green }, savedNoteText: { color: '#315C3F' }, secondary: { minHeight: 40, alignItems: 'center', justifyContent: 'center', marginTop: 8, paddingHorizontal: 10 }, secondaryText: { color: C.plum, fontSize: 9, fontWeight: '600', textAlign: 'center' }, error: { padding: 12, borderRadius: 14, backgroundColor: C.red, marginTop: 10 }, errorTitle: { color: C.redInk, fontSize: 10, fontWeight: '800', marginBottom: 5 },
  urgentBanner: { flexDirection: 'row', gap: 12, padding: 16, borderRadius: 20, backgroundColor: '#7D3935', marginTop: 14, marginBottom: 12 }, urgentMark: { width: 25, height: 25, borderRadius: 14, color: '#7D3935', backgroundColor: '#FFE3D9', textAlign: 'center', textAlignVertical: 'center', fontWeight: '900', fontSize: 17, overflow: 'hidden' }, urgentTitle: { color: C.white, fontSize: 22, fontWeight: '700' }, urgentBody: { color: '#FFE7E2', fontSize: 11, lineHeight: 16, marginTop: 5 }, urgentLine: { flexDirection: 'row', gap: 6, marginTop: 7 }, urgentBullet: { color: '#B44D44', fontSize: 12, fontWeight: '800' }, sourceLink: { marginTop: 10 }, homeAction: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, borderRadius: 14, backgroundColor: C.plum, marginTop: 3 }, homeActionText: { color: C.white, fontSize: 8, fontWeight: '800', letterSpacing: .8 }, homeArrow: { color: C.white, fontSize: 20 },
  modalShade: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(30,23,38,.48)' }, modalShadeWeb: { justifyContent: 'center', alignItems: 'center', padding: 12 }, modalCard: { maxHeight: '90%', paddingHorizontal: 18, paddingTop: 11, paddingBottom: 24, borderTopLeftRadius: 25, borderTopRightRadius: 25, backgroundColor: C.bg }, modalCardWeb: { width: '100%', maxWidth: 390, maxHeight: '92%', alignSelf: 'center', borderRadius: 25, borderWidth: 1, borderColor: '#E6E0EA' }, modalHandle: { alignSelf: 'center', width: 35, height: 4, borderRadius: 3, backgroundColor: '#D7D1DC', marginBottom: 14 }, modalTitle: { color: C.ink, fontSize: 21, fontWeight: '600', marginTop: 4, marginBottom: 8 }, modalToggles: { marginTop: 10 }, confirm: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 13, backgroundColor: C.blue, borderRadius: 14, marginTop: 12 }, confirmText: { color: C.white, fontSize: 8, fontWeight: '800', letterSpacing: .7 }, confirmArrow: { color: C.white, fontSize: 18 }, cancel: { minHeight: 40, alignItems: 'center', justifyContent: 'center' }, cancelText: { color: C.muted, fontSize: 9, fontWeight: '700' },
});
