import React from 'react';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Orb } from '../../src/components/Orb';
import { Label, Pill, Surface } from '../../src/components/Surface';
import { useNura } from '../../src/state/NuraContext';
import { colors, radius } from '../../src/theme';
export default function Profile() {
  const { name, birthday, country, email, phone, updateProfile, topics, facts, assets, addFact } = useNura(); const [detailLabel, setDetailLabel] = React.useState(''); const [detailValue, setDetailValue] = React.useState('');
  return <View style={styles.page}><ScrollView contentContainerStyle={styles.content}><View style={styles.profileHead}><Orb size={56} /><View><Label>YOUR 720 PROFILE</Label><Text style={styles.title}>{name || 'Your profile'}</Text><Text style={styles.sub}>A living picture · you stay in control</Text></View></View>
    <Surface style={styles.summary}><Label>WHAT NU﻿RA CURRENTLY KNOWS</Label><Text style={styles.copy}>{name ? `You’d like Nura to call you ${name}. ` : 'You haven’t added your name yet. '}{topics.length ? `You chose to explore ${topics.map((topic) => topic.label.toLowerCase()).join(', ')}. ` : ''}{assets.length ? `${assets.length} source file${assets.length === 1 ? ' is' : 's are'} stored on this device; contents have not been analyzed. ` : ''}{facts.length ? `${facts.length} confirmed health details are in your registry.` : 'No health facts have been added or confirmed yet.'}</Text><Text style={styles.source}>This summary uses only information you entered in this app.</Text></Surface>
    <Text style={styles.section}>Personal details</Text><TextInput value={name} onChangeText={(value) => updateProfile({ name: value })} placeholder="Name" placeholderTextColor={colors.quiet} style={styles.input} /><TextInput value={birthday} onChangeText={(value) => updateProfile({ birthday: value })} placeholder="Birthday · YYYY-MM-DD" placeholderTextColor={colors.quiet} style={styles.input} /><TextInput value={country} onChangeText={(value) => updateProfile({ country: value })} placeholder="Country" placeholderTextColor={colors.quiet} style={styles.input} /><TextInput value={email} onChangeText={(value) => updateProfile({ email: value })} placeholder="Email" placeholderTextColor={colors.quiet} keyboardType="email-address" autoCapitalize="none" style={styles.input} /><TextInput value={phone} onChangeText={(value) => updateProfile({ phone: value })} placeholder="Phone" placeholderTextColor={colors.quiet} keyboardType="phone-pad" style={styles.input} />
    <Text style={styles.section}>Add a health detail</Text><Text style={styles.help}>Enter a condition, medication, measurement or note. Nura saves this as self-reported, with today’s date.</Text><TextInput value={detailLabel} onChangeText={setDetailLabel} placeholder="What is it? e.g. Medication" placeholderTextColor={colors.quiet} style={styles.input} /><TextInput value={detailValue} onChangeText={setDetailValue} placeholder="Details" placeholderTextColor={colors.quiet} style={styles.input} /><Pressable onPress={() => { if (!detailLabel.trim() || !detailValue.trim()) return; addFact(detailLabel, detailValue); setDetailLabel(''); setDetailValue(''); }} style={styles.add}><Text style={styles.addText}>Save to my registry</Text></Pressable>
    <Text style={styles.section}>Health areas you selected</Text><View style={styles.pills}>{topics.length ? topics.map((topic) => <Pill key={topic.id} selected>{topic.label}</Pill>) : <Text style={styles.empty}>No topics selected yet. You can add them during profile setup.</Text>}</View>
    <Surface style={styles.registry} onPress={() => router.push('/(tabs)/health')}><Text style={styles.registryTitle}>Medical Registry</Text><Text style={styles.registrySub}>{facts.length} confirmed details · {assets.length} source files</Text><Text style={styles.link}>Open registry →</Text></Surface>
    <Surface style={styles.registry} onPress={() => router.push('/privacy')} accessibilityLabel="Open data and privacy controls"><Text style={styles.registryTitle}>Your data & privacy</Text><Text style={styles.registrySub}>Review what’s saved, where it lives and how to clear it.</Text><Text style={styles.link}>Review your data →</Text></Surface>
  </ScrollView></View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.bg }, content: { padding: 22, paddingTop: 43, paddingBottom: 35, maxWidth: 560, width: '100%', alignSelf: 'center' }, profileHead: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 20 }, title: { color: colors.text, fontSize: 30, fontWeight: '300', marginTop: 5 }, sub: { color: colors.muted, fontSize: 11, marginTop: 5 }, summary: { padding: 17 }, copy: { color: colors.text, fontSize: 14, lineHeight: 21, marginTop: 11 }, source: { color: colors.quiet, fontSize: 10, marginTop: 10 }, section: { color: colors.text, fontSize: 19, fontWeight: '300', marginTop: 24, marginBottom: 12 }, input: { minHeight: 50, backgroundColor: '#FFFFFF', borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, color: colors.text, paddingHorizontal: 15, fontSize: 14, marginBottom: 9 }, pills: { flexDirection: 'row', flexWrap: 'wrap' }, empty: { color: colors.quiet, fontSize: 12, lineHeight: 18 }, registry: { marginTop: 10 }, help: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: -4, marginBottom: 10 }, add: { padding: 14, borderRadius: 99, backgroundColor: '#E8E0FF', marginBottom: 8 }, addText: { color: colors.ink, textAlign: 'center', fontSize: 12, fontWeight: '600' }, registryTitle: { color: colors.text, fontSize: 15, fontWeight: '500' }, registrySub: { color: colors.muted, fontSize: 11, marginTop: 6 }, link: { color: colors.violet, fontSize: 11, marginTop: 12 } });
